# Form implementation generated from reading ui file '/home/kkt/development/proj/intranet_sh/모니터링/modules/Ui/circular_progress.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_circular_progress(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)

        self.setupUi(parent)

    def setupUi(self, circular_progress):
        circular_progress.setObjectName("circular_progress")
        circular_progress.resize(341, 363)
        self.circularProgressBar_Main = QtWidgets.QFrame(parent=circular_progress)
        self.circularProgressBar_Main.setGeometry(QtCore.QRect(20, 30, 320, 342))
        self.circularProgressBar_Main.setStyleSheet("background-color: none;")
        self.circularProgressBar_Main.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.circularProgressBar_Main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circularProgressBar_Main.setObjectName("circularProgressBar_Main")
        self.circular_Production_Progress = QtWidgets.QFrame(parent=self.circularProgressBar_Main)
        self.circular_Production_Progress.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.circular_Production_Progress.setStyleSheet("QFrame{\n"
"    border-radius: 150px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.400 rgba(0, 0, 255, 255), stop:0.395 rgba(0, 0, 255, 0));\n"
"}")
        self.circular_Production_Progress.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circular_Production_Progress.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circular_Production_Progress.setObjectName("circular_Production_Progress")
        self.circular_Production_Bg = QtWidgets.QFrame(parent=self.circularProgressBar_Main)
        self.circular_Production_Bg.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.circular_Production_Bg.setStyleSheet("QFrame{\n"
"    border-radius: 150px;    \n"
"    background-color: rgba(85, 85, 127, 100);\n"
"}")
        self.circular_Production_Bg.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circular_Production_Bg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circular_Production_Bg.setObjectName("circular_Production_Bg")
        self.circularContainer = QtWidgets.QFrame(parent=self.circularProgressBar_Main)
        self.circularContainer.setGeometry(QtCore.QRect(40, 40, 220, 220))
        self.circularContainer.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: rgb(58, 58, 102);\n"
"}")
        self.circularContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circularContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circularContainer.setObjectName("circularContainer")
        self.label_line = QtWidgets.QLabel(parent=self.circularContainer)
        self.label_line.setGeometry(QtCore.QRect(20, 50, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_line.setFont(font)
        self.label_line.setStyleSheet("color:white")
        self.label_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_line.setObjectName("label_line")
        self.label_qty = QtWidgets.QLabel(parent=self.circularContainer)
        self.label_qty.setGeometry(QtCore.QRect(30, 130, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_qty.setFont(font)
        self.label_qty.setStyleSheet("color:white")
        self.label_qty.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_qty.setObjectName("label_qty")
        self.circular_TT_Progress = QtWidgets.QFrame(parent=self.circularProgressBar_Main)
        self.circular_TT_Progress.setGeometry(QtCore.QRect(20, 20, 260, 260))
        self.circular_TT_Progress.setStyleSheet("QFrame{\n"
"    border-radius: 130px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.49 rgba(255, 0, 0, 0), stop:0.5 rgba(255, 0, 0, 255));\n"
"}")
        self.circular_TT_Progress.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circular_TT_Progress.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circular_TT_Progress.setObjectName("circular_TT_Progress")
        self.circular_TT_Bg = QtWidgets.QFrame(parent=self.circularProgressBar_Main)
        self.circular_TT_Bg.setGeometry(QtCore.QRect(20, 20, 260, 260))
        self.circular_TT_Bg.setStyleSheet("QFrame{\n"
"    border-radius: 130px;    \n"
"    background-color: rgb(225,225,225);\n"
"}")
        self.circular_TT_Bg.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circular_TT_Bg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circular_TT_Bg.setObjectName("circular_TT_Bg")
        self.circular_Production_Progress.raise_()
        self.circular_TT_Bg.raise_()
        self.circular_Production_Bg.raise_()
        self.circular_TT_Progress.raise_()
        self.circularContainer.raise_()

        self.retranslateUi(circular_progress)
        QtCore.QMetaObject.connectSlotsByName(circular_progress)

    def retranslateUi(self, circular_progress):
        _translate = QtCore.QCoreApplication.translate
        circular_progress.setWindowTitle(_translate("circular_progress", "Form"))
        self.label_line.setText(_translate("circular_progress", "Main 1"))
        self.label_qty.setText(_translate("circular_progress", "266"))
